### ISSUE TITLE
Switching between windows leaves words highlighted in the previously focused one

### ISSUE THREAD

**Issue by arthurxavierx** [RRethy/vim-illuminate#10]
I believe that from https://github.com/RRethy/vim-illuminate/blob/master/plugin/illuminate.vim#L27, the  expected behaviour when switching between windows would be that the previously focused one had its illuminated words unhighlighted; but it's not the case.

Is there a way for me to configure this behaviour on my own? I don't think so, because the illuminate functions are local to the script, and not autoload functions (which would be nice to have, by the way).

**Comment by RRethy** [comment]
Yea the first thing is a bug due to https://github.com/RRethy/vim-illuminate/blob/master/plugin/illuminate.vim#L120, making a fix for it now and will be out in a few.

For your second point I agree, I'll transition the functions to autoload some time tmrw.

**Comment by arthurxavierx** [comment]
Wow, that was fast! Thanks for the awesome work! :)
