### ISSUE TITLE
Highlighting functionality is broken on neovim nightly (0.8.0)

### ISSUE THREAD

**Issue by OlegGulevskyy** [RRethy/vim-illuminate#103]
**Describe the bug**
After switching to neovim nightly, it looks like highlighting is broken for me. Every time I move a cursor, I am having errors in console (I am new to neovim).
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/43781031/175613845-7a4ee86c-1961-4246-b6ae-67e878b09490.png">

**To Reproduce**
Having nightly neovim

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RRethy** [comment]
Insufficient steps to reproduce, no minimal init.lua and nightly works for me. This bug also doesn't look like a vim-illuminate bug.
