### ISSUE TITLE
[Question]: Blacklist/disable vim-illuminate in nvim-tree

### ISSUE THREAD

**Issue by willdavidow** [RRethy/vim-illuminate#104]
**Describe the bug**
I'll start by saying this is not a bug; just a question.

I'm trying to disable `vim-illuminate` in `nvim-tree` but can't seem to get it to stop highlighting things there.

**To Reproduce**
1. Open `nvim-tree`
2. Move cursor down to any repeated character in the tree
3. Observe that multiple instances of that character are highlighted

**Expected behavior**
No items are highlighted in the `nvim-tree` buffer

**Screenshots**
Not-highlighted when cursor is over `space` character(s)
![image](https://user-images.githubusercontent.com/763985/178998811-7cd80bb5-da92-4592-a19a-f76052fe7892.png)

Move cursor over `>` character and all instances are highlighted
![image](https://user-images.githubusercontent.com/763985/178998931-7560ea9b-f850-4721-b254-aee8e1060d1f.png)

I've tried a bunch of items in the blacklist, but nothing seems to be taking hold - I'm sure that I'm doing something incorrectly, either in setting up the blacklist, or just not using the correct terms in it.. 
![image](https://user-images.githubusercontent.com/763985/178999638-11104b8c-3f99-47dc-86fb-f7a63e64de2b.png)

**Comment by RRethy** [comment]
What is the output of `:set ft?`

**Comment by willdavidow** [comment]
> What is the output of `:set ft?`

`filetype=typescriptreact` and `filetype=lua`

**Comment by willdavidow** [comment]
That fixed it, thanks!

**Comment by cj** [comment]
@willdavidow @RRethy I have that set, but it is still highlighting it:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/1819/185803873-c248992e-c60c-4e14-b25f-fc64ba80ee60.png">

**Comment by RRethy** [comment]
What is the output of `nvim -v` or `vim -v` (which ever you are using)? You may want to look at https://github.com/RRethy/vim-illuminate/issues/111.

**Comment by cj** [comment]
@RRethy I switch to v2 and it works now using the new config :)

**Comment by cj** [comment]
Thank you!
