### ISSUE TITLE
How to disable vim-illuminate for only certain words ?

### ISSUE THREAD

**Issue by Flo-Slv** [RRethy/vim-illuminate#105]
Hi there,

it's not about a bug, just an how to do for newbie !

Is it possible to disable words like 'local' or 'function' for lua filetype ?

When I type ```:echo synIDattr(synID(line("."), col("."), 1), "name")``` under lua function keyword, nothing return...

Did I missed something ?

Thanks, Flo !

**Comment by RRethy** [comment]
If `:echo synIDattr(synID(line("."), col("."), 1), "name")` doesn't work then you are probably using tree-sitter which disables standard highlight and syn id. There's no way around that at the moment.

**Comment by Flo-Slv** [comment]
Yep I use tree-sitter.

Thanks for your reply !
