### ISSUE TITLE
don't work with highlight yank

### ISSUE THREAD

**Issue by YuCao16** [RRethy/vim-illuminate#107]
**Describe the bug**
I was using `illuminate` and [highlightedyank](https://github.com/machakann/vim-highlightedyank) before, but I have now given up on `highlightedyank` and use `neovim` build in autocmd as follows:
```
augroup highlight_yank
	autocmd!
	au TextYankPost * silent! lua vim.highlight.on_yank {higroup=(vim.fn['hlexists']('HighlightedyankRegion') > 0 and 'HighlightedyankRegion' or 'IncSearch'), timeout=750}
augroup END
```
This code should highlight the whole line, but miss the word highlighted by `illuminate`:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/62466929/182916771-a6af30fd-5321-49eb-8cc9-717508c718c8.png">

**To Reproduce**
Steps to reproduce the behavior (include minimal `init.vim` or `.vimrc`):
1. Add autocmd to your init.lua
2. Find a word can toggle `illuminate`
3. Double press `y`

**Expected behavior**
The whole line been highlighted.

**Comment by RRethy** [comment]
Please provide a minimal init.vim in the future, what you pasted is not minimal nor can be it used in isolation.

Highlight priority is handling internally in Neovim [here](https://github.com/neovim/neovim/blob/d15a66d80336ff3f6c69a0eff4c17c83a84d44c9/runtime/lua/vim/lsp/util.lua#L1649) and uses [this value](https://github.com/neovim/neovim/blob/d15a66d80336ff3f6c69a0eff4c17c83a84d44c9/runtime/lua/vim/highlight.lua#L9). That's out of scope for this plugin to modify.

**Comment by silentjay** [comment]
Also having this problem, sadly linking neovims internals isn't much help. 

Does anyone have a work around?

**Comment by serranomorante** [comment]
I tried with neovim internals but quickly got tired. I just added some extra lines to my `on_yank` highlight autocmd.

This will "disable" `vim-illuminate` while the yank highlight is visible.

```lua
autocmd("TextYankPost", {
  desc = "Highlight yanked text",
  group = augroup("highlightyank", { clear = true }),
  callback = function()
    local highlight_timeout = 500
    local illuminate_available = utils.is_available("vim-illuminate")
    if illuminate_available then require("illuminate").pause_buf() end

    vim.highlight.on_yank({
      higroup = "Substitute",
      timeout = highlight_timeout,
      on_macro = true
    })

    if illuminate_available then vim.defer_fn(function() require("illuminate").resume_buf() end, highlight_timeout) end
  end,
})
```

`utils.is_available` is just a [helper function](https://github.com/AstroNvim/AstroNvim/blob/b1f824a6cfe7ba7290f851cf9db9bfd7af1e94d3/lua/astronvim/utils/init.lua#L221) to see if `vim-illuminate` exists in my current instance of neovim.

**Comment by rockyzhang24** [comment]
A workaround here. Works well.

```lua
vim.api.nvim_create_autocmd({ 'TextYankPost' }, {
  group = vim.api.nvim_create_augroup('highlight_yank', { clear = true }),
  callback = function()
    local illuminate = require "illuminate"
    illuminate.pause()
    vim.highlight.on_yank({ timeout = 300 })
    illuminate.resume()
  end,
})
```

**Comment by serranomorante** [comment]
Apparently no workaround is needed after this [recent commit](https://github.com/RRethy/vim-illuminate/commit/305bf07b919ac526deb5193280379e2f8b599926). 

Working fine now for me.

**Comment by RRethy** [comment]
Yea when this issue was first opened we weren't using extmarks at the time.
