### ISSUE TITLE
Is it possible to make backwards-compatible EnableIllumination optional?

### ISSUE THREAD

**Issue by arizonatribe** [RRethy/vim-illuminate#108]
The `IlluminationEnable` command is [also mapped to EnableIllumination](https://github.com/RRethy/vim-illuminate/blob/master/plugin/illuminate.vim#L44) for backwards-compatibility.

The issue I'm encountering is I can't use the quick shortcut `:E` to Vim's native `:Explore` command because of `:EnableIllumination`. For now, I'm just typing `:Ex`.

Is it possible to make this optional (perhaps if the user sets a variable) so that this command isn't created when `vim-illuminate` starts up?

**Comment by RRethy** [comment]
`:delcommand EnableIlluminate`

**Comment by RRethy** [comment]
Actually sourcing order might be off.

**Comment by arizonatribe** [comment]
> Actually sourcing order might be off.

Yes, good point. I couldn't invoke `nvim_del_user_command()` in my Neovim config. However I was able to get it to work this way:

```
vim.api.nvim_command('au VimEnter delcommand EnableIllumination')
```

**Comment by RRethy** [comment]
The change I pushed removes those commands so updating the plugin should make that command redundant.

**Comment by arizonatribe** [comment]
Awesome! Thanks so much for all the work you've put into this library. Really enjoying it
