### ISSUE TITLE
Error during error reporting

### ISSUE THREAD

**Issue by Diablo-D3** [RRethy/vim-illuminate#113]
```
Error executing vim.schedule lua callback: ...undle/start/vim-illuminate.git/lua/illuminate/engine.lua:139: attempt to perform arithmetic on a string value
stack traceback:
        ...undle/start/vim-illuminate.git/lua/illuminate/engine.lua:139: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>
```

Using otherwise vanilla Illuminate config. Seems to have been introduced with: https://github.com/RRethy/vim-illuminate/blob/09235da12cfdad2a4f695610a079b20f1b263b4a/lua/illuminate/engine.lua#L139

**Comment by RRethy** [comment]
I fixed the string handling, if you see the real internal error you can reopen with it and I'll take a look.

**Comment by Diablo-D3** [comment]
```
vim-illuminate: An internal error has occured: false"...le/start/vim-illuminate.git/lua/illuminate/highlight.lua:38: hl_group is not a valid highlight"
```

I'm not sure which highlight group is being called.

**Comment by RRethy** [comment]
I suspect there's an LSP that's not providing `kind` information in the return data, this is causing [kind_to_hl_group](https://github.com/RRethy/vim-illuminate/blob/c5af6c73cde7f5910e28c13f40eefc81f974e82f/lua/illuminate/highlight.lua#L39) to return `nil` which is an invalid highlight group. I though LSP servers had to provide `kind` for `documentHighlight` but they can violate things at times 🤷 . That's my best guess at least.

**Comment by Diablo-D3** [comment]
This is with rust-analyzer, I do not currently have any other LSPs installed (although I suspect I should install sumneko lua for neovim config reasons; would also provide an alternate LSP to help debug issues in LSP ecosystem plugins).

**Comment by RRethy** [comment]
Just checked the spec, `kind` is an optional field https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight.
