### ISSUE TITLE
Use CursorWorld highlighting group

### ISSUE THREAD

**Issue by Shatur** [RRethy/vim-illuminate#128]
I would like to suggest to add `CursorWord`, `CursorWord0` and `CursorWord1` and fallback to them from `Illuminated*` highlights.
Many colorschemes use them, it would simplify like for colorscheme developers.

**Comment by RRethy** [comment]
I don't see many colorschemes using those highlights (I looked at 15 repos), the only one was [sonokai](https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim) which also specifies the vim-illuminate highlight groups anyways.

As for the highlight groups themselves, they are not documented in the plugin I'm assuming you found them from [vim-cursorword](https://github.com/itchyny/vim-cursorword/blob/master/doc/cursorword.txt), their behaviour is not specified, only their name is mentioned briefly.

I'm not going to add unnecessary complexity to have compatibility with a lesser used Vim plugin that uses cryptic highlight group names which lack documentation.

**Comment by Shatur** [comment]
> I don't see many colorschemes using those highlights (I looked at 15 repos)

Hm... Strange, I assumed it used more often.

> I'm assuming you found them from [vim-cursorword](https://github.com/itchyny/vim-cursorword/blob/master/doc/cursorword.txt)

The group `CursorWorld` is also used [here](https://github.com/yamatsum/nvim-cursorline). But I see your point. Names `Illuminated*` just unique and it forces colorscheme authors to add more highlighting groups.
