### ISSUE TITLE
How to disable highlight in dashboard?

### ISSUE THREAD

**Issue by longguzzz** [RRethy/vim-illuminate#136]
The `filetypes_denylist` seems the most relavent options, but it doesn't work.
![image](https://user-images.githubusercontent.com/96779663/192962749-411cdffd-7eee-43e6-9c8b-211364aae146.png)

**Comment by RRethy** [comment]
Please use the issue template.

**Comment by longguzzz** [comment]
> Please use the issue template.

Sorry, there is a templete for reporting bug, but this issue is not about a bug.

It is more like asking whether a feature exists. And if the feature doesn't exist, no need for debugging is required. That's why I leave no information for debugging.

If a template for Q&A exists, I am happy to ask questions following the template.

**Comment by RRethy** [comment]
If `filetypes_denylist` doesn't work, then that is a bug.

**Comment by longguzzz** [comment]
> If `filetypes_denylist` doesn't work, then that is a bug.

The problem has been solved now. I mistook the `filetypes_denylist` for file name of configuration, then I used `dashboard` from my `dashboard.lua` config. Now `alpha` works in place of `dashboard`.
![image](https://user-images.githubusercontent.com/96779663/193570700-bb7a168b-a4d3-4a00-937a-3183960ff157.png)
