### ISSUE TITLE
Highlight changed from illumated background to underline

### ISSUE THREAD

**Issue by OlegGulevskyy** [RRethy/vim-illuminate#138]
**Describe the bug**
Before I moved from 0.7 to 0.8, I had illuminate highlighted in a nice way
<img width="488" alt="image" src="https://user-images.githubusercontent.com/43781031/193684429-18c31453-fe1b-43ff-b3ce-0c85bdce9417.png">

Now it's just underlined like so
<img width="355" alt="image" src="https://user-images.githubusercontent.com/43781031/193684359-6a503546-eb27-456c-8514-451c2038127c.png">

**To Reproduce**
Use neovim 0.8, I guess ? I am not sure if I am the only one affected, or if I am overwriting something accidentally

**Output from `:IlluminateDebug`**
```
buf_should_illuminate 11 true
config {
  delay = 100,
  filetype_overrides = {},
  filetypes_allowlist = {},
  filetypes_denylist = { "dirbuf", "dirvish", "fugitive" },
  modes_allowlist = {},
  modes_denylist = {},
  providers = { "lsp", "treesitter", "regex" },
  providers_regex_syntax_allowlist = {},
  providers_regex_syntax_denylist = {},
  under_cursor = true
}
started true
provider table: 0x0109490088 lsp
```

**Expected behavior**
Highlighted as before, in a nice "illuminated" way

**Comment by Allaman** [comment]
Hmm I don't think that is Neovim 0.8 related. It is just the new default highlighting of vim-illuminate. Please refer to https://github.com/RRethy/vim-illuminate/issues/115 I guess that should help you

**Comment by RRethy** [comment]
As @Allaman mentioned, it's related to https://github.com/RRethy/vim-illuminate/issues/111, you'll need to define `IlluminatedWordText`, `IlluminatedWordRead`, `IlluminatedWordWrite` highlight groups (default to underline).

**Comment by OlegGulevskyy** [comment]
Thanks for the pointer, indeed that's the change.
I was wondering though why this was changed to underline by default, as to me this makes little sense - it was highlighting it the way you'd expect a package called "illuminate", so it's illuminating words :)
