### ISSUE TITLE
Disabling highlights in visual mode

### ISSUE THREAD

**Issue by richardhttps** [RRethy/vim-illuminate#141]
**Describe the bug**
Not a bug

An issue like this was closed with no obvious answer.

Selecting highlighted text in visual mode makes it unclear what is selected and what is not.
I've read the docs, it''s not clear whether there is an option to disable highlights in visual mode.  
There's this:
`modes_denylist: modes to not illuminate, this overrides modes_allowlist`
But not sure if it's what I'm looking for and what's required syntax.

**Comment by serranomorante** [comment]
Additionally, for `visual block mode` is not intuitive that you should actually use `"\22"` 😫
