### ISSUE TITLE
Illuminate not highlighting words in latex text

### ISSUE THREAD

**Issue by andy941** [RRethy/vim-illuminate#144]
I can't see any highlight/underline in latex files. I installed this plugin specifically to help with my thesis writing, English is not my first language and helps avoiding word repetition.
The plugin works perfectly for a number of file types, I checked lua, C++, vimscript and R so far. It doesn't show any highlighting in latex files. Is it a known issue? I checked with the debug function and it doesn't seem to be anything different between when it works and when it doesn't. The LSP provider for latex is texlab and I have the treesitter parser installed for latex. I am using the default configuration with no changes.
Minimal example to reproduce:

``` tex
\documentclass[draft,11pt,a4paper]{report}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\begin{document}
the quick brown fox jumped over the lazy dog.
\end{document}

```

putting the cursor on `the` doesn't highlight/underline the other. Same with `\usepackage`.

Thank you, the plugin is beautiful.
Andrea

**Comment by RRethy** [comment]
Closing because the issue template was not followed.
