### ISSUE TITLE
Feature Request: Illuminate the closest parenthesis under the cursor

### ISSUE THREAD

**Issue by kaykhan** [RRethy/vim-illuminate#149]
Hi,

Would it be possible to "illuminate" the closest parenthesis under the cursor word like it does in vscode. See example screenshot.

You can see how the closest parenthesis "{ }" have been Illuminate with a block cursor.
![image](https://user-images.githubusercontent.com/5202527/208931143-109ea06d-5f67-42d3-8535-141a0a09f972.png)

**Comment by RRethy** [comment]
It's possible but will require code changes. I'll leave this issue since I wouldn't be opposed to adding this, just not sure when I'll get around to it.

**Comment by utilyre** [comment]
Hello, I've recently made a plugin that does exactly that! See https://github.com/utilyre/sentiment.nvim

**Comment by kaykhan** [comment]
> Hello, I've recently made a plugin that does exactly that! See https://github.com/utilyre/sentiment.nvim

Hey, i just got around to trying this. Works nicely, thanks

**Comment by unphased** [comment]
I'll note this functionality is also possible with vim-matchup.
