### ISSUE TITLE
bad argument #1 to 'ipairs' (table expected, got nil)"

### ISSUE THREAD

**Issue by fgheng** [RRethy/vim-illuminate#156]
**Describe the bug**
Sometimes an error was occured
```
ERROR vim-illuminate: An internal error has occured: false"...share/nvim/lazy/vim-illuminate/lua/illuminate/engine.lua:176: bad argument #1 to 'ipairs' (table expected, got nil)"
```
I don't know how to use the common method to reproduce. I can only reproduce it on my environment.
But I think the below code will solve this problem

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/50551377/215403532-a7ed490e-72fd-4ace-876b-f9467f35c7e0.png">

**To Reproduce**
Steps to reproduce the behavior (include minimal `init.vim` or `.vimrc`):

**Note** Omitting a minimal `init.vim`/`init.lua`/`.vimrc` will likely result in the issue being closed without explanation.

**Output from `:IlluminateDebug`**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RRethy** [comment]
Please fill in the issue template or the issue will be closed. I'm not going to add random null checks everywhere without understanding first why a function that should never return nil is returning nil.
