### ISSUE TITLE
`Invalid buffer id` from popup windows

### ISSUE THREAD

**Issue by SichangHe** [RRethy/vim-illuminate#159]
Please see [this issue I posted in glepnir/lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim/issues/813).

Copied here:

> ### Describe the bug
> Moving down in the window opened by `:Lspsaga outline` throws errors:
> 
> ```viml
>    Error  10:36:25 msg_show.lua_error Error executing vim.schedule lua callback: ...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:166: Invalid buffer id: <BUFFER_ID>
> stack traceback:
> 	[C]: in function 'nvim_buf_attach'
> 	...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:166: in function 'save'
> 	...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:229: in function 'handler'
> 	...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
> 	vim/_editor.lua: in function <vim/_editor.lua:0>
> ```
> 
> ### Steps to reproduce
> Using this `init.lua`:
> 
> ```lua
> require('packer').startup(function(use)
>     use {
>         'glepnir/lspsaga.nvim',
>         event = 'VimEnter',
>         requires = { 'nvim-tree/nvim-web-devicons' },
>         config = function()
>             require('lspsaga').setup {
>                 lightbulb = {
>                     enable_in_insert = false,
>                     virtual_text = false,
>                 },
>                 symbol_in_winbar = {
>                     enable = false,
>                 },
>                 ui = {
>                     border = 'none',
>                 },
>             }
>         end,
>     }
> 
>     use {
>         'mhanberg/elixir.nvim',
>         ft = { 'elixir' },
>         config = function()
>             local ex = require('elixir')
>             ex.setup {
>                 cmd = 'elixir-ls',
>                 settings = ex.settings {
>                     enableTestLenses = true,
>                     suggestSpecs = true,
>                 },
>             }
>         end
>     }
> end)
> ```
> 
> (I suspect that it does not have to be an Elixir LS, but any LS.)
> 
> Open up a new Neovim session and `:PackerCompile`.
> 
> Reopen Neovim in a project so that the buffer has LSP attached. It seems that the buffer needs to have functions.
> 
> Run `:Lspsaga outline`.
> 
> Press down j for a little while.
> 
> See demo video below: [![demo video](https://camo.githubusercontent.com/0c18fd6071bcaf43cdd7f87e038ec2b9ca14ef6b9520104edfeb1c857e20648c/68747470733a2f2f61736369696e656d612e6f72672f612f6c75396935684f44316d31574f48326f4e70624c4833514f582e737667)](https://asciinema.org/a/lu9i5hOD1m1WOH2oNpbLH3QOX)
> 
> ### Expected behavior
> No error should occur.
> 
> Also, the floating window should be above the outline window, but that is another bug.
> 
> ### Neovim version (nvim -v)
> NVIM v0.8.2
> 
> ### lspsaga commit
> [54725e8](https://github.com/glepnir/lspsaga.nvim/commit/54725e87bdc3adf6cd609a5f54c03ef08091b1f2)
> 
> ### Terminal name/version
> alacritty 0.11.0 (8dbaa0b)

**Output from `:IlluminateDebug`**
```lua
buf_should_illuminate 1 true
config {
  delay = 100,
  filetype_overrides = {},
  filetypes_allowlist = {},
  filetypes_denylist = { "dirbuf", "dirvish", "fugitive" },
  min_count_to_highlight = 1,
  modes_allowlist = {},
  modes_denylist = {},
  providers = { "lsp", "treesitter", "regex" },
  providers_regex_syntax_allowlist = {},
  providers_regex_syntax_denylist = {},
  under_cursor = true
}
started true
provider table: 0x01050789c0 treesitter
`termguicolors` false
```

This does not do anything because of the minimum `init.lua`, but I still get the error.

**Additional context**
The author of `lspsaga.nvim` suggested me [a way to check which plugin caused the problem](https://github.com/glepnir/lspsaga.nvim/issues/813#issuecomment-1413235821).
I tried the command `au CursorMoved`, and to my surprise, although `vim_illuminate` is not added to `packer`,

```vim
:au CursorMoved
--- Autocommands ---
matchparen  CursorMoved
    *         call s:Highlight_Matching_Pair()
vim_illuminate_v2_augroup  CursorMoved
    *         <Lua 38: ~/.local/share/nvim/site/pack/packer/start/vim-illuminate/lua/illuminate/engine.lua:47>
```

**Comment by RRethy** [comment]
I would strongly suggest you create an actual minimal init.lua instead of just guessing what parts of your config are causing the error. This is unrelated to vim-illuminate.

**Comment by RRethy** [comment]
> I tried the command au CursorMoved, and to my surprise, although vim_illuminate is not added to packer,

That is an issue with packer, not vim-illuminate, packer has installed vim-illuminate into the `start/`. This is why `:IlluminateDebug` exists and even though you said `This does not do anything because of the minimum init.lua`, that is incorrect, you just don't see the highlighting because `termguicolors` is turned off. You can validate this with `:set termguicolors`.

Personally, I would avoid packer like the plague, but in the meantime you can use `nvim --clean` to avoid loading plugins and help narrow down the issue.

**Comment by SichangHe** [comment]
I apologize for my mistakes.

I just wiped `vim-illuminate` and the problem persisted.

For the Packer issues, what plugin manager would you suggest?
