### ISSUE TITLE
vim.treesitter.query.get_query() is deprecated

### ISSUE THREAD

**Issue by nimaaskarian** [RRethy/vim-illuminate#164]
**Describe the bug**
When I open up some certain .sh or .py in my LunarVim (Neovim) that has vim illuminate installed in it, I get this nasty warning of 
`vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated
This feature will be removed in Nvim version 0.10`
and when I continue, it says the error is happening inside `...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:140: in function <...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:118>
   [C]: in function 'pcall'
   ...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:118: in function ''
   vim/_editor.lua: in function <vim/_editor.lua:0>`

I haven't recently configed my LunarVim (as you can see in my [dotfiles](https://github.com/nimaaskarian/dotfiles/tree/master/.config) repo), but this warning is very recent. 
This error won't appear when I open a new buffer. it just appears when I load LunarVim initially with a shell file that is not empty (`lvim Scripts/wal.sh`) or I use alpha.nvim or `:e` to open the file up

**To Reproduce**
Steps to reproduce the behavior (include minimal `init.vim` or `.vimrc`):
I don't really know...

**Note** Omitting a minimal `init.vim`/`init.lua`/`.vimrc` will likely result in the issue being closed without explanation.

**Output from `:IlluminateDebug`**

**Expected behavior**
Not to get this nasty warning...

**Screenshots**

**Additional context**

**Comment by RRethy** [comment]
This is an issue your local version of nvim-treesitter, please open the issue there.

**Comment by nimaaskarian** [comment]
> This is an issue your local version of nvim-treesitter, please open the issue there.
Sorry, I had no idea about whats going on. Thanks for leading me to the right direction
