### ISSUE TITLE
Request clarification in documentation for 

### ISSUE THREAD

**Issue by unphased** [RRethy/vim-illuminate#165]
**Describe the bug**
In the help and readme, it says:

> ==============================================================================
> 4. Highlight Groups                              *illuminate-highlight-groups*
> 
> 
> ILLUMINATEDWORDTEXT
> 
> Default highlight group used for references if no kind information is
> available.
> 
> 
>     hi def IlluminatedWordText gui=underline
> 
> 
> 
> ILLUMINATEDWORDREAD
> 
> Highlight group used for references of kind read.
> 
> 
>     hi def IlluminatedWordRead gui=underline
> 
> 
> 
> ILLUMINATEDWORDWRITE
> 
> Highlight group used for references of kind write.
> 
> 
>     hi def IlluminatedWordWrite gui=underline
> 

It's not clear what this means. What is a read/write "kind" of reference?

**Comment by unphased** [comment]
Simple testing reveals that the highlights correspond to whether a given symbol/variable/token is being set or read. something like that.

**Comment by fent** [comment]
after reading that, i still don't understand :/

**Comment by unphased** [comment]
i noticed this only really works on very few languages. basically this plugin uses treesitter to differentiate between when a given highlighted symbol is in a "read" context or a "write" context. 

For example when you assign a variable e.g. `let x = "42"` and you put your cursor on some later reference to `x`, the style you gave `IlluminatedWordWrite` will be applied to the `x` in the assignment statement but not to the other references of it. Make sense?

I find very little value in this because it only works on like 2% of languages in my experience.

**Comment by RRethy** [comment]
Some languages have an LSP or treesitter queries which differentiate read/write, others just use `text` because it's easier. It's not up to vim-illuminate, but we will interpret them appropriately if they are available. As OP said, it's rare they are implemented.
