### ISSUE TITLE
getting error on fedora nvim

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [RRethy/vim-illuminate#166]
**Describe the bug**
everytime i open i get

stack traceback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:200: in function 'get_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:169: in function 'prepare_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:288: in function 'iter_captures' ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:50: in function 'fn' ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:356: in function 'get_indents' ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:98: in function 'get_indent' ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:466: in function '' vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated stack traceback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:274: in function 'get_node_text' ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:214: in function 'find_definition' ...t/vim-illuminate/lua/illuminate/providers/treesitter.lua:16: in function 'get_references' ...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:130: in function <...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:108> [C]: in function 'pcall' ...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:108: in function '' vim/_editor.lua: in function <vim/_editor.lua:0> Press ENTER or type command to continue

treesitter bug request https://github.com/nvim-treesitter/nvim-treesitter/issues/4813
the config i am using
https://github.com/LunarVim/Neovim-from-scratch

**Comment by RRethy** [comment]
Please use the issue template.
