### ISSUE TITLE
Sublanguage inner support for treesitter

### ISSUE THREAD

**Issue by unphased** [RRethy/vim-illuminate#167]
**Describe the bug**
When my cursor is on a large vimL lua string literal, treesitter is able to properly syntax highlight the vimL content of the string literal, but illuminate just highlights the entire string literal instead of highlighting the vimL symbols inside of it. 

In the below reproduction case (minimal init provided): 

**Observed behavior**:
treesitter based provider is not able to properly illuminate symbols that are inside an embedded language. It either highlights the whole string literal or highlights nothing at all. 

**To Reproduce**
Steps to reproduce the behavior (include minimal `init.vim` or `.vimrc`):

Minimal lua init script is below. Note treesitter highlight must be properly enabled to get nested language highlights to show up.

```lua
vim.cmd([[
    set nocompatible

    " load illuminate 
    let &rtp  = '~/.local/share/nvim/lazy/vim-illuminate/,' . &rtp
    let &rtp .= ',~/.local/share/nvim/lazy/vim-illuminate/after'

    " load treesitter
    let &rtp  = '~/.local/share/nvim/lazy/nvim-treesitter,' . &rtp
    let &rtp .= ',~/.local/share/nvim/lazy/nvim-treesitter/after'

    hi IlluminatedWordText ctermfg=green
    hi IlluminatedWordRead ctermfg=red
    hi IlluminatedWordWrite ctermfg=blue
]])

require('nvim-treesitter.configs').setup{
    auto_install = true,
    highlight = {
        enable = true,
        disable = {},
    },
}

require('illuminate').configure({
    -- providers: provider used to get references in the buffer, ordered by priority
    providers = {
        'lsp',
        'treesitter',
        -- 'regex',
    },
})
```

**Output from `:IlluminateDebug`**

```
buf_should_illuminate 1 true
config {
  delay = 100,
  filetype_overrides = {},
  filetypes_allowlist = {},
  filetypes_denylist = { "dirbuf", "dirvish", "fugitive" },
  min_count_to_highlight = 1,
  modes_allowlist = {},
  modes_denylist = {},
  providers = { "lsp", "treesitter" },
  providers_regex_syntax_allowlist = {},
  providers_regex_syntax_denylist = {},
  under_cursor = true
}
started true
provider table: 0x7ff1d88fccb0 treesitter
`termguicolors` false
```

**Expected behavior**
Illuminate's behavior inside a sublanguage string should be the same as if it was in a buffer with that string's contents. 

**Screenshots**

![image](https://github.com/RRethy/vim-illuminate/assets/1542910/b7c6ef13-1153-4845-a5c6-218a0fab6cdf)

Cursor is on one of the `require` tokens. See red fgcolor to indicate illuminate is working on the require token as well as output of `:Inspect`.

![image](https://github.com/RRethy/vim-illuminate/assets/1542910/7f3cae24-ac83-4862-8ea2-bce498158e66)

Cursor is on one of the `hi` tokens near the top of the screenshot.

**Comment by unphased** [comment]
in the meantime I will re-enable `regex` provider to get reasonable behavior, however the behavior is still bad because (and i am not sure what other plugin interactions are potentially causing this) in my main config instead of failing to match, illuminate actually matches the entire lua string. So I don't think regex provider can kick in in that situation.

**Comment by RRethy** [comment]
Support for injected languages with tree-sitter was intentionally omitted for performance reasons, there's no efficient way to reasonably support it.

**Comment by unphased** [comment]
makes sense. still hoping for a way to let it fallback to `regex` provider when cursor is on a string though. I'm not sure why my minimal reproduction isn't able to replicate this.

**Comment by RRethy** [comment]
I'm going to close this, an issue could be created in nvim-treesitter such that the `nvim-treesitter.locals` will be aware of injected languages which would then be usable by vim-illuminate, but there wouldn't be code changes in vim-illuminate. As for falling back to regex provider when a cursor is on a string, we don't really know we're on a string that has an injected language without a series of brittle hacks.
