### ISSUE TITLE
illuminating across visible buffers?

### ISSUE THREAD

**Issue by towc** [RRethy/vim-illuminate#17]
Hey again!

One thing I enjoy about incsearch is that it highlights results across all visible buffers. It would be nice for this plugin too.

**Comment by RRethy** [comment]
Implementation is a little tricky but I'll try it out over the next couple of days. Will try to make it an option to opt into.

**Comment by RRethy** [comment]
Not possible afaik. Only option would be to use search highlighting, but that would clutter up the search history.

**Comment by sunaku** [comment]
You can use `:keeppatterns` to avoid modifying the search history. :neckbeard:
