### ISSUE TITLE
nvim-treesitter deprecations

### ISSUE THREAD

**Issue by RRethy** [RRethy/vim-illuminate#179]
See https://github.com/nvim-treesitter/nvim-treesitter/issues/5378

**Comment by davidpdrsn** [comment]
Could this be causing

> vim-illuminate: An internal error has occured: false"...im/0.9.1/share/nvim/runtime/lua/vim/treesitter/que
ry.lua:259: query: invalid structure at position 2992 for language lua"

Errors being printed on start up? I tried https://github.com/RRethy/vim-illuminate/pull/182 but that didn't help.

**Comment by RRethy** [comment]
Try updating nvim-treesitter and running `:TSInstall! lua`

**Comment by davidpdrsn** [comment]
That did it. Thanks!
