### ISSUE TITLE
Disable default keybindings

### ISSUE THREAD

**Issue by abhinavnatarajan** [RRethy/vim-illuminate#180]
Is there a way to disable the default keybindings? I like to explicitly set all my own keybindings in a separate config file to make it easier for me to remember what keys I've bound and for what plugins.

**Comment by RRethy** [comment]
You can still set you own keymaps and ignore those from vim-illuminate, [vim-illuminate won't override any existing keymaps](https://github.com/RRethy/vim-illuminate/blob/6acf7d4a18255a3ddc43770866c8e148fe85af7b/lua/illuminate/util.lua#L47-L49).
