### ISSUE TITLE
[Feature Request] Box outline similar to VSCode

### ISSUE THREAD

**Issue by habanerotostitos** [RRethy/vim-illuminate#183]
Hi,

Firstly, thank you for the plugin!

I'm not sure if this is even possible in vim/neovim, but would love this option if it is possible.

Included a photo below.

![box](https://github.com/RRethy/vim-illuminate/assets/146843573/53bb7c8e-4fe1-4d3c-9f15-873cd8bdd437)

**Comment by RRethy** [comment]
That's not possible inside a terminal.
