### ISSUE TITLE
[Question] Highlight except unused variables/functions

### ISSUE THREAD

**Issue by lan1812783** [RRethy/vim-illuminate#189]
When my cursor is on an **unused** variable, I can barely see what text is underneath it because illuminate is highlighting the variable, here is an example:
![with cursor](https://github.com/RRethy/vim-illuminate/assets/65657562/704c4828-995e-490c-be5f-b0fd2f99286a)
For comparison, this is what it looks like without the cursor:
![Without cursor](https://github.com/RRethy/vim-illuminate/assets/65657562/c6e8c7f6-4eae-4595-8738-30bd6f4c7b8f)
My question is how can I configure illuminate to not highlight unused variables/functions?
I know there is 'min_count_to_highlight' config and I could change it to 2 instead of 1 by default, but it would be nice if I needn't to change that.

**Comment by RRethy** [comment]
You can change the hlgroup being used, the default is just an underline which means you've already changed the hlgroup (or your colorscheme). Adding an additional LSP call would slow the plugin down for minimal return, additionally as you said there is a simple config fix for that specific use-case.
