### ISSUE TITLE
spelling/grammar suggestions

### ISSUE THREAD

**Issue by valacar** [RRethy/vim-illuminate#19]
Hello. I just wanted to offer some spelling and grammar fixes in the docs and readme. I'm not confident enough to make a pull request, so here is a `git diff` of the changes I made....

https://gist.github.com/valacar/5a5044e7ad100c0649ce06313003c32f

A short overview of changes:
* "overriden" -> "overridden"
* "uses of current word" -> "uses of the current word"
* "but will a little bit" -> "but with a little bit"
* "millis" -> "milliseconds"
* "cursorline" -> "CursorLine"
* "But it can be overriden" -> "It can however be overridden"

I think that's it. Hopefully it helps. Also thanks for making such a cool plugin...really loving it :)

**Comment by RRethy** [comment]
Thanks mate!
