### ISSUE TITLE
Moving between references in macOS

### ISSUE THREAD

**Issue by spring-haru** [RRethy/vim-illuminate#190]
**It is not a bug,,,,,**
The README.md says "You'll also get <a-n> and <a-p> as keymaps to move between references", and  `<a>` is often interpreted as the `option` key in macOS. But, `<option-n>` and `<option-p>` do not work. Is this an expected result? What am I missing? 

**To Reproduce**
Use `vim-illuminate` and `<option-n>` and `<option-p>` in macOS.

**Output from `:IlluminateDebug`**
None

**Expected behavior**
Hopefully, `<option-n>` and `<option-p>` make it possible to jump other ref.

**Screenshots**
None

**Additional context**
None

macOS 14.2.1
nvim 0.9.5 Release

**Comment by spring-haru** [comment]
I decided to use
```
vim.keymap.set('n', '<C-n>', require('illuminate').goto_next_reference, { desc = "Move to next reference" })
vim.keymap.set('n', '<C-p>', require('illuminate').goto_prev_reference, { desc = "Move to previous reference" })
```
Thanks for the great plugin!

**Comment by RRethy** [comment]
I use MacOS, you likely already have a mapping for `<a-n>` and `<a-p>` which is causing vim-illuminate to not override that existing mapping, see [the source code](https://github.com/RRethy/vim-illuminate/blob/3bd2ab64b5d63b29e05691e624927e5ebbf0fb86/plugin/illuminate.vim#L33-L38).
