### ISSUE TITLE
Flashing for lua_ls highlights

### ISSUE THREAD

**Issue by Twotyth** [RRethy/vim-illuminate#195]
**Description**
Highlight flashes in normal mode (insert is fine) when using lua_ls as source; does not happen with other languages servers, checked on csharp_ls and clangd;
If reference highlight resolved by vim.lsp.buf.document_highlight - it flashes in normal mode for lua_ls too, while others are fine.

**Reproduction**
1. Enter .lua file with lsp configured and it being a source for illuminate
2. Bug happens

**Output from `:IlluminateDebug`**
![image](https://github.com/RRethy/vim-illuminate/assets/104644578/146b6dbe-8e62-4226-93cb-21ac701013cb)

**Expected behavior**
Consistent highlighting

**Example**
if needed, I can capture a video of flashing but i doubt that'll be needed

**Comment by RRethy** [comment]
Can you capture a video. I use lua ls and I don't see flashing.

**Comment by RRethy** [comment]
Can you also create a minimal init.lua that only startups vim-illuminate to rule out other plugins/config being an issue.

**Comment by RRethy** [comment]
Closing, can reopen when there is a minimal init.lua.

From the bug report template:

```
**Note** Omitting a minimal `init.vim`/`init.lua`/`.vimrc` will likely result in the issue being closed without explanation.
```

**Comment by ku1ik** [comment]
I'm also observing flashing / blinking of the highlight when moving cursor left and right within a highlighted symbol in lua_ls buffers. Issue doesn't occur in other lsp buffer (rust, elixir, etc).

**Comment by jb49088** [comment]
same
