### ISSUE TITLE
How to highlight WORD (not word) ?

### ISSUE THREAD

**Issue by shellwhale** [RRethy/vim-illuminate#206]
From my understanding, by default only word (using w) are highlighted.
Is it possible to also have the WORD highlighted (using W)? Maybe some kind of background color

**Comment by RRethy** [comment]
Neither `word` nor `WORD` is being highlighted.

For Treesitter, it's using the query files for each language.
For LSP, it's using whatever the LSP server decides.
For regex, it's using this algorithm, https://github.com/RRethy/vim-illuminate/blob/5eeb7951fc630682c322e88a9bbdae5c224ff0aa/lua/illuminate/providers/regex.lua#L6-L28, which is similar to `word` but has various differences with edge cases.

You can get what you are looking for with the `case_insensitive_regex` config option.
