### ISSUE TITLE
Does not work out of the box without `termguicolors`

### ISSUE THREAD

**Issue by kovasap** [RRethy/vim-illuminate#207]
**Describe the bug**
With [my config](https://github.com/kovasap/dotfiles/blob/d10932e7f5eecc9868e480d934a02255640afbc4/.vim/init.lua#L543), I can only get illuminate to visually work when I `:set termguicolors`.

Is there a specific set of highlight groups my colorscheme must define for illuminate to work?

**To Reproduce**
Steps to reproduce the behavior (include minimal `init.vim` or `.vimrc`):
1. Load https://github.com/kovasap/dotfiles/blob/master/.vim/init.lua
2. Open a file
3. Mouse over a symbol

**Output from `:IlluminateDebug`**

```
buf_should_illuminate 1 true
config {
  case_insensitive_regex = false,
  delay = 100,
  filetype_overrides = {},
  filetypes_allowlist = {},
  filetypes_denylist = { "dirbuf", "dirvish", "fugitive" },
  min_count_to_highlight = 1,
  modes_allowlist = {},
  modes_denylist = {},
  providers = { "lsp", "treesitter", "regex" },
  providers_regex_syntax_allowlist = {},
  providers_regex_syntax_denylist = {},
  under_cursor = true
}
started true
provider table: 0x7fdf32031330 treesitter
`termguicolors` false
```

**Expected behavior**
Common symbols should illuminate on mouse over.

**Comment by RRethy** [comment]
That is not a minimal config, your colorscheme is likely the issue.

**Comment by kovasap** [comment]
Yes I realize that - by filing this issue I was hoping to learn more about
what illuminate requires from a color scheme to work.  That would help me
figure out what I would need to change with my color scheme.  Are these
requirements documented anywhere?

**Comment by kovasap** [comment]
Turns out my issue was that I was defining the illuminate highlight groups like in the readme:

```
vim.cmd('hi IlluminatedWordText gui=underline')
vim.cmd('hi IlluminatedWordRead gui=underline')
vim.cmd('hi IlluminatedWordWrite gui=underline')
```

When I should have been doing:

```
vim.cmd('hi IlluminatedWordText cterm=underline')
vim.cmd('hi IlluminatedWordRead cterm=underline')
vim.cmd('hi IlluminatedWordWrite cterm=underline')
```
