### ISSUE TITLE
Illuminates even when word is not directly under cursor

### ISSUE THREAD

**Issue by andersevenrud** [RRethy/vim-illuminate#3]
Hi,

Great work. It behaves very nice after the delay changes. There's only one thing that kind of feels weird, which is that it will highlight words that are not directly under the cursor. When I'm over a whitespace it will highlight the "next word". 

Attaching a screenshot for demonstration.

![2018-07-28-203336_3840x2160_scrot](https://user-images.githubusercontent.com/161548/43359637-d0513bee-92a5-11e8-9f7f-56253c3eaac3.png)

Thought I'd make a proper issue instead of filling up your Reddit thread, heh.

**Comment by RRethy** [comment]
That's a known issue unfortunately. It's happening since expand('<cword>') is what is used to get the word under the cursor, but if it has none, then it returns the first word in front of it. Currently, I dont have a fix, but I'll leave the issue open in case I find a fix in the future.

**Comment by andersevenrud** [comment]
I see. I'm pretty sure I'll get used to it :) I guess that also kinda answers #4  -- which I can probably override just by using a vim setting.

**Comment by RRethy** [comment]
Looked into a bit more, the similar behaviour will happen if you are at the start of the line and press `*`, it will highlight the first word it finds. Don't think there is a nice fix unfortunately :/

**Comment by andersevenrud** [comment]
Indeed. For `*` usage it "feels" pretty natural since you're not jumping between whitespaces very often, but in this case it just initially felt weird. But now that I know the mechanics, it's all good :)

**Comment by lewis6991** [comment]
Instead of using `expand('<cword>')`, can you use this instead?

```vim
let l:line = getline('.')
let l:col = col('.') - 1
let l:word = matchstr(l:line[:l:col], '\k*$') . matchstr(l:line[l:col:], '^\k*')[1:]
```

**Comment by RRethy** [comment]
@lewis6991 Very clever, makes sense! Merging it in now!

**Comment by lewis6991** [comment]
Don't give me all the credit, I just looked at how https://github.com/itchyny/vim-cursorword handled it.

**Comment by towc** [comment]
btw, I actually preferred it this way. Can this be left as an option?
