### ISSUE TITLE
add option to overwrite the hightlight color

### ISSUE THREAD

**Issue by thallysrc** [RRethy/vim-illuminate#31]
I'm recently installed this plugin but this highlight don't have to much difference in my colorscheme, probably my eyes doesn't work so well, my suggestions is to add an option to overwrite this color to turn this hightlight a little more comfortable to me, if the owner of repository think that could be useful i volunteer myself to do this.
![Screenshot from 2019-03-11 10-09-05](https://user-images.githubusercontent.com/10141867/54126541-8ede8e80-43e6-11e9-971f-7c8b4cdf9de9.png)

**Comment by RRethy** [comment]
This already exists and is documented in the README and help docs. You have access to the highlight group which defines how the colouring is done. Here are some examples to get you started:

> Underline the words

```vim
hi illuminatedWord cterm=underline gui=underline
```

> Dark Red

```vim
hi illuminatedWordk ctermbg=4 guibg=#8b0000
```

> White

```vim
hi illuminatedWordk ctermbg=15 guibg=#FFFFFF
```
