### ISSUE TITLE
Mention autocompletion for better search results

### ISSUE THREAD

**Issue by technicalpickles** [RRethy/vim-illuminate#32]
I was looking for this plugin's exact functionality after trying Visual Studio Code. I came across things like https://www.reddit.com/r/vim/comments/4h3oa2/how_to_automatically_underline_word_under_cursor/ but all the results I found were pretty old plugins. It took someone suggesting this plugin to find it.

I think if you include like auto somewhere, that might help get picked up more.

**Comment by RRethy** [comment]
I changed the tagline in the project description and at the top of the README to fit what I assume would be more likely for people to search for. ty
