### ISSUE TITLE
Fails to work after d293eb

### ISSUE THREAD

**Issue by xxdavid** [RRethy/vim-illuminate#33]
Hi, thank you for this great plugin again, it helps me everyday!

However, probably after commit d293eb5400, it suddenly stopped working.
Any time I move my cursor on a word, this error pops up:
```
Error detected while processing function <SNR>140_illuminate:                                                                                                                                 
line    9:                                                                                                                                                                                    
E492: Not an editor command:  index(g:Illuminate_ftHighlightGroups[&filetype], synIDattr(synID(line('.'), col('.'), 1), 'name')) >= 0
```

Running `:echo index(g:Illuminate_ftHighlightGroups[&filetype], synIDattr(synID(line('.'), col('.'), 1), 'name')) >= 0` works though (prints `0`).

Do you know what could be the cause?

I'm using neovim 0.3.5 (tested on 0.3.1 too).

**Comment by bobrippling** [comment]
Let me know if my [change](https://github.com/bobrippling/vim-illuminate/tree/fix-newline) / 255c816 fixes this.

**Comment by xxdavid** [comment]
@bobrippling, yep, this fixes it! Thank you!

**Comment by RRethy** [comment]
Oops, thanks for the fix @bobrippling . Weird that it continued to work for me even without the `\`, might be due some difference with how Neovim interprets vimscript.

**Comment by bobrippling** [comment]
Yeah, `:help line-continuation` in Neovim says nothing about it either 🤔
