### ISSUE TITLE
Configurable valid word characters

### ISSUE THREAD

**Issue by andersevenrud** [RRethy/vim-illuminate#4]
Could it maybe be possible to add configuration for how vim-illuminate recognizes a word ? I was doing some CSS editing and noticed that strings with underscores were completely highlighted, while the hyphens were not (which you find a lot in CSS).

**Comment by RRethy** [comment]
Check out `:h iskeyword` and `:set iskeyword?`. The highlighting is configurable with the `iskeyword` option.

You can use `:set iskeyword+=-` which would highlight the whole string with the hyphen. However, I would make sure to use that only for the languages you want to behave like that, maybe use it in an autocmd as such:

```
autocmd FileType css setlocal iskeyword+=-
```
