### ISSUE TITLE
Is there a way to change the colour of the highlight?

### ISSUE THREAD

**Issue by hrai** [RRethy/vim-illuminate#41]
I use solarised scheme and the highlight colour is almost invisible. Is there a way to change this value via config?

**Comment by RRethy** [comment]
Please read the README or the docs before asking a question. The highlight group `illuminatedWord` controls the appearance.

```
hi illuminatedWord cterm=underline gui=underline
```

**Comment by suntzuisafterU** [comment]
I read the readme, and the docs.

Same question, is there a way to specify the color of the highlighting?

I am using Visual highlighting, and would prefer the color to be something similar the example at the top of the README.md

**Comment by suntzuisafterU** [comment]
See `:help hi` for details, and `:hi` for a list of existing highligh groups.

To set the colours for a highlight group add something like this to your vimrc:
```
:hi illuminatedWord ctermbg=242
```
Can also set `ctermfg guibg guifg` etc.

**Comment by RRethy** [comment]
The readme example uses `:hi illuminatedWord guibg=#2c313c` (with `:set termguicolors` on). As you mentioned, `:h hi` will have more info on customization.

**Comment by suntzuisafterU** [comment]
Thanks!  This looks great
