### ISSUE TITLE
Stopped working suddenly

### ISSUE THREAD

**Issue by mectos** [RRethy/vim-illuminate#42]
Hello,
The plugin just stopped working (I think after downloading python syntax plugins), are you familiar with the problem?

Thanks in advance

**Comment by RRethy** [comment]
Does it not work for all filetypes? Did your colorscheme change? What happens when you run `hi illuminatedWord cterm=underline gui=underline`.

**Comment by mectos** [comment]
Fixed it, your suggestion helped me.
Thank you for your time!

**Comment by RRethy** [comment]
Interesting, I'm able to reproduce now. It seems somewhere between `init.vim` gets loaded (and illuminatedWord is defined), it gets cleared (`hi illuminatedWord` will say `illuminatedWord xxx cleared`). Seems to be related to [this closed nvim issue](https://github.com/neovim/neovim/issues/5730). Any highlight group defined in your init.vim gets cleared.

A quick hack for this would be to create a file `~/.config/nvim/after/plugin/illuminate_hack.vim` that has one line:

```vim
hi illuminatedWord cterm=underline gui=underline
```

This will be loaded after so it won't be cleared. Maybe tn I'll implement a variable that takes highlight values and define the highlight group myself in the plugin to circumvent this issue.
