### ISSUE TITLE
Blacklisting other languages than VimScript

### ISSUE THREAD

**Issue by mectos** [RRethy/vim-illuminate#43]
Hello,
I saw your example of how to blacklist a language highlighting, this one:
```
let g:Illuminate_ftHighlightGroups = {
      \ 'vim:blacklist': ['vimVar', 'vimString', 'vimLineComment',
      \         'vimFuncName', 'vimFunction', 'vimUserFunc', 'vimFunc']
      \ }
```
So I tried to implement that on other language (JS, in my case), and I didn't work to my regret.
Tried this:
```
let g:Illuminate_ftHighlightGroups = {
      \ 'vim:blacklist': ['vimVar', 'vimString', 'vimLineComment',
      \         'vimFuncName', 'vimFunction', 'vimUserFunc', 'vimFunc']
      \ 'js:blacklist': ['jsString', 'jsLineComment']
      \ }
```
Is there a reason behind the failure?

Thank you very much in advance man!

**Comment by RRethy** [comment]
`js` is not a filetype, look at the output of `:set ft?` when you have a javascript file open.

**Comment by mectos** [comment]
Changed it ```'javascript:blacklist'```, still doesn't work though :(

**Comment by RRethy** [comment]
`['jsString', 'jsLineComment']` those also don't look like real highlight groups, use `:echo synIDattr(synID(line("."), col("."), 1), "name")` to determine highlight groups.

**Comment by mectos** [comment]
Yes, that's what was missing
Thanks man!
