### ISSUE TITLE
Toggle buffer only

### ISSUE THREAD

**Issue by juanMarinero** [RRethy/vim-illuminate#44]
How can I apply `IlluminationToggle` just in current **buffer**? Please.
From the [doc - COMMANDS](https://github.com/RRethy/vim-illuminate/blob/master/doc/illuminate.txt) section, I tried in vain to map either globally OR buffer-range:
```
nnoremap <buffer> <leader>aht  <Esc>:IlluminationToggle<CR>
nnoremap          <leader>ahtg <Esc>:IlluminationToggle<CR>
```
Since the toggle function is ([source](https://github.com/RRethy/vim-illuminate/blob/master/autoload/illuminate.vim))
```
fun! illuminate#toggle_illumination() abort
  if !s:enabled
    call illuminate#enable_illumination()
  else
    call illuminate#disable_illumination()
  endif
endf
```
...I tried to build my own mini function, but these also affect all buffers:
```
nnoremap <buffer> <leader>asd1 <Esc>:call illuminate#disable_illumination()<CR>
nnoremap <buffer> <leader>asd2 <Esc>:call illuminate#enable_illumination()<CR>
```
Thanks in advance!

**Comment by RRethy** [comment]
You can enable and disable at a buffer level using a bang, for example

```vim
IlluminateDisable!
IlluminateEnable!
IlluminateToggle!
```

Without the bang will apply globally (however, any previously used bang calls will override all future global invocations).

I'm going to leave this undocumented for a bit so it can be tested.

**Comment by juanMarinero** [comment]
Thanks @RRethy !! It works.

Might someone just copy-paste:
```
nnoremap <buffer> <leader>aht <Esc>:IlluminationToggle!<CR>:echo "---- Auto highlight wordUnderCursor toogled BUFFER (add g to map global)----"<CR>
nnoremap          <leader>ahtg <Esc>:IlluminationToggle<CR>:echo "---- Auto highlight wordUnderCursor toogled GLOBALLY (all buffers) ----"<CR>
```

**Comment by RRethy** [comment]
In the mapping you don't need `<buffer>` since that just means "make this mapping only for this buffer", it doesn't modify the functionality of the executed command.
