### ISSUE TITLE
[Feature Request] Support highlight twins of word under cursor

### ISSUE THREAD

**Issue by kevinhwang91** [RRethy/vim-illuminate#45]
I think it's very useful. 
Highlight the word in the current line with the bold or italic style is awesome.

**Comment by RRethy** [comment]
I'm not sure what you mean, can you elaborate? If this is about customizing the appearance of the highlighting we have `g:Illuminate_hl_link` which can be used as :

```vim
    let g:Illuminate_hl_link = 'hi illuminatedWord cterm=underline gui=underline'
```

**Comment by kevinhwang91** [comment]
No, like this project. https://github.com/dominikduda/vim_current_word

**Comment by RRethy** [comment]
Is this to support different highlight group for matches of the word under the cursor?

**Comment by kevinhwang91** [comment]
Yes.

**Comment by RRethy** [comment]
Interesting, yea that's doable. [This line](https://github.com/RRethy/vim-illuminate/blob/2e3bb036ab5aad459c4e021122ea08d06d6bacc2/autoload/illuminate.vim#L86) would need to be modified to have 2 calls to matchadd using the pattern on line 88 if the person has opted in for the different highlights. I'm open to PRs, if not when I'm free I'll implement it.

**Comment by RRethy** [comment]
You can use something like this to get the behaviour.

```vim
augroup illuminate_augroup
    autocmd!
    autocmd VimEnter * hi illuminatedWord cterm=italic gui=italic | hi illuminatedCurWord cterm=bold gui=bold
augroup END
```
