### ISSUE TITLE
mbyte character support

### ISSUE THREAD

**Issue by suliveevil** [RRethy/vim-illuminate#48]
Would you please add mbyte character support?
Highlight all the same single character in range `[\u4e00-\u9fa5] ` is all I need.
Thank you very much.

**Comment by RRethy** [comment]
I'm not sure what you mean. Can you provide an example and what you expect to be highlighted based on your cursor position.

**Comment by suliveevil** [comment]
Treat character that in range of [\u4e00-\u9fa5] as a word.
Then we can achieve 

> Highlight all the same single character in range `[\u4e00-\u9fa5] `

![treat chinese character as a word](https://user-images.githubusercontent.com/35763237/85961626-551c0780-b9de-11ea-85db-7161f1e74637.png)

**Comment by suliveevil** [comment]
Chinese character and word is different from English letter and word because they don't have delimiters.

So we can treat the tiniest textobj of Chinese i.e. character in range `[\u4e00-\u9fa5] ` as a word.

Then we can highlight the same `pseudo word` as usual.

**Comment by suliveevil** [comment]
If we have a this match pattern , we can even do more on it: 
use text segmentation to highlight other textobj.

**Comment by RRethy** [comment]
> use text segmentation to highlight other textobj.

What does this mean?



As for matching specific unicode characters as whole words, vim-illuminate uses `\k` which is controlled by `:h 'iskeyword'` which doesn't support unicode characters AFAIK. vim-illuminate loosely highlights the same thing matched by the motion `iw` (try `viw` on your text and you will see what it highlights). To add support for matching specific unicode characters I would likely add an option to match against a regex pattern along the lines of `[a-z]` but with unicode characters. However, I'm not sure about adding this, I'm going to think about this for a couple of days.

**Comment by suliveevil** [comment]
Text segmentation should be done by tools like jieba or other natural language grammar checkers.

**Comment by RRethy** [comment]
> Text segmentation should be done by tools like jieba or other natural language grammar checkers.

For the record I was confused by `textobj` because it means something very different than simply the tokens in a document, for example vim-illuminate to an extent highlights the text object `iw`, while there are no text objects for single unicode characters.

**Comment by suliveevil** [comment]
You are right. Thank you very much.
I realized that I should make a custom textobj to cooperate with vim-illuminate, that's Vim way.
I will learn to write plugins.
