### ISSUE TITLE
Bad highlighting in folded lines

### ISSUE THREAD

**Issue by lervag** [RRethy/vim-illuminate#52]
In neovim v0.5 (nightly), I experience a strange bug where vim-illuminate highlighting for some reason breaks the highlighting of folded lines.

I made a minimal example:

```vim
syntax enable

set termguicolors
highlight Folded gui=bold guibg=white guifg=red
highlight MyWord gui=bold guibg=red   guifg=white

nnoremap q :qall!<cr>

silent edit test.txt
normal! zM
redraw!
sleep 1

normal! zR
redraw!
sleep 1

call matchadd('MyWord', '\V' . 'test', -1)
redraw!
sleep 1

normal! zM
```

where `text.txt` contains e.g. this:

```
{{{ test 1

}}}
{{{ test 2

}}}
{{{ test 3

}}}
{{{ test 2

}}}
{{{ test 3

}}}
{{{ test 2

}}}
{{{ test 3

}}}

# vim: fdm=marker
```

I believe this is really a bug with neovim which is already discussed here: https://github.com/neovim/neovim/issues/12982. However, vim-illuminate relies on this specific feature and so becomes partly broken because of this bug. Thus, I thought it was polite to mention it here. It might be OK to simply close the issue again immediately.

**Comment by RRethy** [comment]
I'll take a look, thanks for letting me know. I've been using an older version of Neovim so didn't notice.

**Comment by lervag** [comment]
No problem. :)

**Comment by RRethy** [comment]
I can' seem to reproduce with your example.

<img width="1392" alt="Screen Shot 2020-11-18 at 9 37 16 PM" src="https://user-images.githubusercontent.com/21000943/99613843-54642c00-29e6-11eb-868b-ddf2677de847.png">
<img width="1392" alt="Screen Shot 2020-11-18 at 9 37 20 PM" src="https://user-images.githubusercontent.com/21000943/99613853-56c68600-29e6-11eb-94da-6fd41c7e8f5f.png">
<img width="1392" alt="Screen Shot 2020-11-18 at 9 37 25 PM" src="https://user-images.githubusercontent.com/21000943/99613856-575f1c80-29e6-11eb-9fb3-2055aa567bb0.png">
<img width="1392" alt="Screen Shot 2020-11-18 at 9 37 33 PM" src="https://user-images.githubusercontent.com/21000943/99613858-57f7b300-29e6-11eb-973c-71159b48cec8.png">

Will leave open though and watch the issue on neovim.

**Comment by lervag** [comment]
Which version of neovim? I'm on 0.5.0-839 (compiled from nightly a few days ago).

**Comment by RRethy** [comment]
Nvm I was using and older version of Neovim (0.5.0-541). I see the behaviour you mentioned. It seems even my `'cursorline'` is affecting the fold highlighting.

<img width="1392" alt="Screen Shot 2020-11-21 at 11 54 04 PM" src="https://user-images.githubusercontent.com/21000943/99894928-f12c0100-2c54-11eb-9a7a-62d03054ead1.png">
<img width="1392" alt="Screen Shot 2020-11-21 at 11 54 08 PM" src="https://user-images.githubusercontent.com/21000943/99894929-f25d2e00-2c54-11eb-89e6-ba3c85ba809c.png">
<img width="1392" alt="Screen Shot 2020-11-21 at 11 54 13 PM" src="https://user-images.githubusercontent.com/21000943/99894930-f426f180-2c54-11eb-82bd-863a38863be4.png">
<img width="1392" alt="Screen Shot 2020-11-21 at 11 54 18 PM" src="https://user-images.githubusercontent.com/21000943/99894933-f6894b80-2c54-11eb-92f4-0692114d5d8f.png">


I'll keep an eye on the linked issue.

**Comment by RRethy** [comment]
https://github.com/neovim/neovim/pull/13393
