### ISSUE TITLE
Is there a way not use this plugin highlight word in fold?

### ISSUE THREAD

**Issue by zdmgmail** [RRethy/vim-illuminate#54]
sometimes it highlight many fold really annoy

![1](https://user-images.githubusercontent.com/50515839/99904430-afa75e80-2d05-11eb-83b6-0da23fc71a61.png)

after I press j: 

![2](https://user-images.githubusercontent.com/50515839/99904538-5f7ccc00-2d06-11eb-87e5-20efa28e8a65.png)

I hope not use this plugin highlight word in fold or not highlight when cursor on a fold

**Comment by RRethy** [comment]
What version of Neovim are you using? This is a bug in Neovim that is being investigated, see #52 and https://github.com/neovim/neovim/issues/12982.

**Comment by RRethy** [comment]
Dup of #52.

**Comment by zdmgmail** [comment]
> What version of Neovim are you using? This is a bug in Neovim that is being investigated, see #52 and [neovim/neovim#12982](https://github.com/neovim/neovim/issues/12982). There is nothing that can be changed in vim-illuminate, closing this issue since #52 is tracking this already.

`NVIM v0.5.0-856-g7dfeadb0f`

**Comment by RRethy** [comment]
Yup that version has the bug. You can try downgrading your neovim version, nvim-0.5.0-840ish  from `brew install --head neovim` doesn't have it.
