### ISSUE TITLE
Error "table index is nil" when using server that doesn't support 'textDocument/documentHighlight'

### ISSUE THREAD

**Issue by jemag** [RRethy/vim-illuminate#57]
Plugin does not seem to work with lsp configuration for terraformls language server.
![image](https://user-images.githubusercontent.com/7985687/103466867-2d07bb00-4d17-11eb-8d90-9f2459a7a586.png)

Does work properly for others, like gopls, bashls, tsserver with same configuration:
``` lua
-- common attach config
local on_attach_common = function(client)
    print("LSP STARTED")
    require'completion'.on_attach(client)
    require'illuminate'.on_attach(client)
end

require'lspconfig'.tsserver.setup{
  on_attach = function(client)
  on_attach_common(client)
  end,
}

require'lspconfig'.bashls.setup{
  on_attach = function(client)
  on_attach_common(client)
  end,
}

require'lspconfig'.terraformls.setup{
  on_attach = function(client)
  on_attach_common(client)
  end,
}

```

**Comment by jemag** [comment]
Same problem with jsonls:
![image](https://user-images.githubusercontent.com/7985687/103467074-1b271780-4d19-11eb-9360-650e175a9065.png)
and same configuration as working ones again:
``` lua
require'lspconfig'.jsonls.setup{
  on_attach = function(client)
  on_attach_common(client)
  end,
}

```

**Comment by RRethy** [comment]
Unrelated, but you can use the following syntax for your config:

```lua
require'lspconfig'.gopls.setup{
  on_attach = on_attach_common
}
```

As for the error, those language servers don't support `textDocument/documentHighlight` which is the part of the LSP that vim-illuminate uses. The best I can do is improve the error message (or I might just hide the error msg) so it makes more sense, but this will mean vim-illuminate doesn't work for those language servers. You can still use normal vim-illuminate functionality (regex based highlighting) if you don't call `require 'illuminate'.on_attach` for those language servers.

**Comment by RRethy** [comment]
Turns the lsp client returns a nil bufnr when the server doesn't implement a call, now it fails silently.

**Comment by jemag** [comment]
Thank you for the clarification and the lua tip
