### ISSUE TITLE
goyou integration, illumination breaks on entering/leaving distraction free mode

### ISSUE THREAD

**Issue by dpopchev** [RRethy/vim-illuminate#59]
After exiting the distraction free mode, provided by the aforementioned [goyo](https://github.com/junegunn/goyo.vim),  the illumination is not working:

Steps to reproduce:
1. open file, all is fine
2. enter distraction free mode, all is fine
3. exit distraction free mode, illumination stops working
4. enter distraction free mode again, all is fine

It seems the plugin is clearing the highlight, as on step.3 I can check that

```
:hi illuminatedWord
illuminatedWord xxx cleared
```

I attempted to
```
augroup illuminate_augroup
    autocmd!
    autocmd BufEnter * hi illuminatedWord cterm=bold,underline
    autocmd BufLeave * hi illuminatedWord cterm=bold,underline
augroup END
```
but this is not sufficient. 

NOTE: if the `autocmd` is applied at VimEnter, not BufEnter, then step 4 is not reproduced.

**Comment by RRethy** [comment]
That plugin appears to have `GoyoEnter` and `GoyoLeave` autocmds you could try. Maybe this could work:

```vim
autocmd! User GoyoLeave nested hi illuminatedWord cterm=bold,underline
```

**Comment by dpopchev** [comment]
Thanks, worked like a charm!
