### ISSUE TITLE
How to enable inversed highlight?

### ISSUE THREAD

**Issue by quantum-booty** [RRethy/vim-illuminate#62]
The [srcery](https://github.com/srcery-colors/srcery-vim) colour scheme has an inversed highlight option which looks like this:
![image](https://user-images.githubusercontent.com/28958399/104380262-a32fcd00-5522-11eb-9950-6c0e7b73c5f9.png)

Whereas vim-illuminate does looks like this:
![image](https://user-images.githubusercontent.com/28958399/104380301-b17de900-5522-11eb-83e3-347321c7417f.png)

Is is possible to enable this inverse highlighting with illuminate?

```
let g:python3_host_prog = '/home/henryw/virtualenvs/data_sci/bin/python'
au BufNewFile,BufRead *.py set filetype=python

call plug#begin('~/.config/nvim/plugged')
Plug 'RRethy/vim-illuminate'
Plug 'srcery-colors/srcery-vim'
call plug#end()

let g:Illuminate_delay = 10
let g:Illuminate_highlightUnderCursor = 0

set termguicolors

let g:srcery_italic = 1
let g:srcery_bold = 1
let g:srcery_inverse_matches = 1
let g:srcery_inverse = 1
let g:srcery_italic_types = 1
let g:srcery_inverse_match_paren = 1
colorscheme srcery
```

**Comment by RRethy** [comment]
For non-lsp highlighting, it is done using `:h illuminatedWord` (which defaults to `CursorLine`) and `:h illuminatedCurWord` (which defaults to the same as `illuminatedWord`). While for the lsp highlighting, it is done using the highlight groups `LspReferenceText`, `LspReferenceRead`, and `LspReferenceWrite`.

To get inverse highlighting, you can use the `inverse` attr for `gui` (see `:h attr-list` in the Neovim help docs) as follows:

```vim
hi illuminatedWord gui=inverse
hi LspReferenceText gui=inverse
hi LspReferenceRead gui=inverse
hi LspReferenceWrite gui=inverse
```
