### ISSUE TITLE
Invalid expression: .pat..'$'

### ISSUE THREAD

**Issue by apemost** [RRethy/vim-illuminate#67]
#### environment

- vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15) Included patches: 1-1453
- OS: Ubuntu 18.04

#### actual behavior

```
Error detected while processing function illuminate#on_cursor_moved[1]..<SNR>223_should_illuminate_file[4]..<SNR>223_list_contains_pat:
line    2:
E15: Invalid expression: .pat..'$'
Error detected while processing function illuminate#on_cursor_moved[1]..<SNR>223_should_illuminate_file[4]..<SNR>223_list_contains_pat:
line    2:
E15: Invalid expression: a:val =~# '^'..pat..'$'
```

#### expected behavior

No errors.

#### screen shot (if possible)

![image](https://user-images.githubusercontent.com/13079610/109189065-91527280-77ce-11eb-9860-83b2928a7a92.png)

**Comment by apemost** [comment]
Lua offers a string concatenation operator, denoted by "..''. 

But [strings can be concatenated with "." in vimscript](http://vimdoc.sourceforge.net/htmldoc/usr_41.html):

	:echo "foo" . "bar"
 	foobar

**Comment by RRethy** [comment]
String concatenation can be done in vimscript with `..`.

https://vimhelp.org/eval.txt.html#expr6:

```
For String concatenation ".." is preferred, since "." is ambiguous, it is also
used for |Dict| member access and floating point numbers.
```

The vim help you linked is for version 7.3.

It seems you are using an early 8.0 version which doesn't have this upgrade in the expression parsing, I'll merge the change, but you need to upgrade your Vim version since many plugins devs (and myself) won't go out of our way to support old version of Vim (5 years old in this case).

**Comment by apemost** [comment]
Can we add a compatibility check?

Patch 8.1.1114
Problem:    Confusing overloaded operator "." for string concatenation.
Solution:   Add ".." for string concatenation.  Also "let a ..= b".
Files:      src/eval.c, src/testdir/test_eval_stuff.vim, runtime/doc/eval.txt

**Comment by RRethy** [comment]
Compatibility check wouldn't be beneficial since it's adding a lot of logic (check for patch for Neovim and Vim) while the reward is just syntactical.
