### ISSUE TITLE
Needs to call next_reference again in the same word when `reverse=true`

### ISSUE THREAD

**Issue by baldore** [RRethy/vim-illuminate#69]
Hello, first at all, what an amazing plugin. Thanks for the great work.

Second, when I use `lua require"illuminate".next_reference{reverse=true,wrap=true}` and I'm in the word, but not at the beginning of the word, it goes to the beginning of the word first, instead of going to the previous match. Adding a gif to be more clear.

![double_back_reference](https://user-images.githubusercontent.com/3131037/113064318-a0309a00-916b-11eb-9584-c44ac4c97893.gif)

Just to know if this is expected or easily fixable. Thanks in advance.

**Comment by RRethy** [comment]
This was expected since it matches the behaviour of `N` when doing `/` searches. I can add an option to override this.

**Comment by RRethy** [comment]
I remember now why I made this decision originally. Matches can be nested, for example:

```
  return true
//             ^cursor is here
```

A language server could return the matches `return true` and `true` so moving to previous without using an ordering based on the start of the match would be weird and skip matches.

**Comment by RRethy** [comment]
You can use `lua require"illuminate".next_reference{reverse=true,wrap=true,range_ordering='disjoint'}` now.

**Comment by baldore** [comment]
Sounds good to me! Thanks for taking a look at this.
