### ISSUE TITLE
change color of highlight

### ISSUE THREAD

**Issue by orengriffin** [RRethy/vim-illuminate#7]
I'm using the ondark theme and the highlight background color as very hard to notice.
could there be a configuration to change the color?
it would probably be best if it was the same like the selection ('V' and select) color.
<img width="303" alt="screen shot 2018-07-29 at 20 14 53" src="https://user-images.githubusercontent.com/7240295/43368914-4d02249c-936d-11e8-973d-bcc0cd69a7cd.png">

**Comment by RRethy** [comment]
Hey, at the bottom of the README and docs there is a section on changing the highlighting. You have to define the `illuminatedWord` highlight group. The following is an example to make it underline the words:

`hi illuminatedWord cterm=underline gui=underline`

To make it the same as the visual selection, you can use the following:

`hi link illuminatedWord Visual`

Drop that in your vimrc OR your colorscheme file.

I am also open to suggestions to improvements to the README and docs to make this more clear, Ill also go back and reread the stuff cuz it was written fairly quickly and maybe not the clearest.

**Comment by kaykhan** [comment]
```hi illuminatedWord cterm=underline gui=underline```

Should this still work for the latest?
