### ISSUE TITLE
vim-illuminate does not work in NVIM v0.5.0-dev+1231-g48e805728

### ISSUE THREAD

**Issue by dstadelm** [RRethy/vim-illuminate#70]
After investigation I know this is not an issue of vim-illuminate. But I don't know how I should report this in nvim as I can't formulate what actually is broken in nvim 0.5.0 a colorscheme is also required.

It seems that highlight groups aren't applied when sourcing in init.vim the first time. I checked out the competition like vim_current_word and though they work with the default settings, when overriding the highlight groups they are only applied if I resource the files for the highlight settings.

Minimal config:

call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
packadd minpac
command! PackUpdate call minpac#update()
command! PackClean  call minpac#clean()
"install/source onedark	
call minpac#add('joshdick/onedark.vim',  {'type': 'opt'})
packadd onedark.vim
set termguicolors
colorscheme onedark
set colorcolumn=120
set background=dark
"install/source illuminate 
call minpac#add('RRethy/vim-illuminate', {'type': 'opt'})
packadd vim-illuminate
hi link illuminatedWord Visual

**Comment by RRethy** [comment]
Try (`:h illuminatedWord`):

```vim
autocmd VimEnter * hi link illuminatedWord Visual
```

**Comment by dstadelm** [comment]
Oh dear, I think I searched help but my eyes skipped this. Thank you for the hint.

However I think this is not the issue I was hunting down. The highlight line in my minimal config is probably misleading and can be discarded. The default highlighting does not work in nvim 0.5.0 but it actually does in nvim 0.4.4.

Maybe it will be fixed in nvim anyhow sometime, I don't know if there is a necessity to take any action, I only wanted to point it out.

**Comment by RRethy** [comment]
Your version of Neovim won't matter so it's config related. I'm going to close this but if you want to figure it out, try with `nvim --clean` and manually load the plugin.

**Comment by dstadelm** [comment]
Well I think I disagree

Using the config shown in the images and starting nvim with -u

With nvim 0.4.4 the result looks like this (call highlighted)
![image](https://user-images.githubusercontent.com/3010527/114608435-f9d1b200-9c9d-11eb-9bf0-3a3199638466.png)
with nvim 0.5.0 the result looks like this (call not highlighted)
![image](https://user-images.githubusercontent.com/3010527/114608599-24bc0600-9c9e-11eb-87c3-bd7743b05f3c.png)

**Comment by RRethy** [comment]
What is the output of `:echo exists('g:loaded_illuminate')`? I use nvim 0.5.0 and this plugin doesn't use fancy features, it uses parts of the api that have been available and stable for years. Make sure this plugin is up to date as well.

**Comment by dstadelm** [comment]
The output is 1

**Comment by RRethy** [comment]
What about:

```vim
echo g:Illuminate_ftHighlightGroups
echo g:Illuminate_ftblacklist
echo g:Illuminate_ftwhitelist
echo g:Illuminate_delay
echo g:Illuminate_highlightUnderCursor
echo g:Illuminate_highlightPriority
echo g:Illuminate_insert_mode_highlight
echo b:illuminate_enabled
```

And can you screenshot the output from:

```vim
hi illuminatedWord
hi illuminatedCurWord
```

**Comment by dstadelm** [comment]
![image](https://user-images.githubusercontent.com/3010527/115262771-215cca80-a135-11eb-8c9d-4ce169be24d0.png)

![image](https://user-images.githubusercontent.com/3010527/115262835-2caff600-a135-11eb-9b2b-7dd1374206dd.png)

![image](https://user-images.githubusercontent.com/3010527/115262931-45201080-a135-11eb-9a5a-aad837d86c58.png)
![image](https://user-images.githubusercontent.com/3010527/115263069-654fcf80-a135-11eb-83fc-af5ed90078c5.png)

**Comment by RRethy** [comment]
`illuminatedWord` is being cleared somewhere in your nvim config.
