### ISSUE TITLE
Bug with g:Illuminate_highlightUnderCursor = 0

### ISSUE THREAD

**Issue by dstadelm** [RRethy/vim-illuminate#71]
When moving the cursor in a group of equal words the highlighting setting does not follow the cursor

Initial situation
![image](https://user-images.githubusercontent.com/3010527/114140578-bf1ff080-9910-11eb-86b5-f29b9c4a485e.png)

Moving cursor one up
![image](https://user-images.githubusercontent.com/3010527/114140765-fe4e4180-9910-11eb-8ad7-2f07fe6bce2e.png)

**Comment by dstadelm** [comment]
I'm sorry to say that the issue remains with me, it does not bother me but I just wanted to let you know.

**Comment by RRethy** [comment]
Fixed again, this was a regression due to another commit.
