### ISSUE TITLE
Need a way to configure the highlight color

### ISSUE THREAD

**Issue by scottchiefbaker** [RRethy/vim-illuminate#73]
The default highlight color for vim-illuminate is pretty subtle. I'd like a way to configure the highlight color (and background) of words. I don't see anything in the documentation about changing the highlight color. Is this possible?

**Comment by RRethy** [comment]
See `:h illuminatedWord` and `:h illuminatedCurWord`. If you are using the LSP functionality then see `:h hl-LspReferenceText`, `:h hl-LspReferenceWrite`, and `:h hl-LspReferenceRead`.

**Comment by scottchiefbaker** [comment]
In case anyone else is looking to do this here is the solution I came up with for my `~/.vimrc`

    autocmd VimEnter * hi illuminatedWord ctermbg=38 ctermfg=226
