### ISSUE TITLE
text object for the highlighted phrase

### ISSUE THREAD

**Issue by tydra-wang** [RRethy/vim-illuminate#80]
Feature request!

I'm using neovim lspconfig with illuminate. It works well, but I am wondering if iluuminate can provide a text object for the highlighed phrase.

For example:
```go
func myfunc() (io.Reader, error)
```

When I put cursor on `io.Reader`, it's highlighted. 
It would be excellent if I can use something like `cix` when I want to change it to `*tar.Reader` !

**Comment by RRethy** [comment]
Interesting, I'd be open to adding this. I'm open to PRs if you can't wait, otherwise when I have time this month I'll try to prototype it out.
