### ISSUE TITLE
Option to disable in visual mode

### ISSUE THREAD

**Issue by igormorgado** [RRethy/vim-illuminate#81]
Is possible to disable  vim-illuminate while in visual mode and visual-block mode?

**Comment by RRethy** [comment]
AFAIK there's no way to react to changing modes, the other option would be adding checks for the mode in callbacks from `CursorMoved` but this has some pretty obvious bugs, thus I don't think this is doable.

**Comment by atusy** [comment]
FYI: `ModeChanged` event helped me.

https://vimhelp.org/autocmd.txt.html#ModeChanged
