### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by jemag** [RRethy/vim-illuminate#83]
**Describe the bug**
Latest commits trigger "attempt to index a nil value"

**To Reproduce**
1. Put cursor on word
2. Notice following error:
![image](https://user-images.githubusercontent.com/7985687/132264120-6b259e2c-94bc-4768-b9e7-d1a198114490.png)

**Expected behavior**
No error and illuminates words

**Additional context**
Works fine if I specify the commit before the latest updates like so : 
```lua
 use {
      'RRethy/vim-illuminate',
      config = function() require 'plugin-configs/vim-illuminate' end,
      commit = '8fe150bd775f659da7e40ea2d3ad7473e6d29494'
    }

```

**Comment by RRethy** [comment]
What's the output from `nvim -v` and `:echo has('nvim-0.5.1')`?

**Comment by jemag** [comment]
nvim -v:
`NVIM v0.6.0-dev+189-g274a3504a`

echo has('nvim-0.5.1'):
`1`

**Comment by RRethy** [comment]
You'll have to update Neovim to a more recent version of master.
