### ISSUE TITLE
next_reference without lsp

### ISSUE THREAD

**Issue by RaZ0rr-Two** [RRethy/vim-illuminate#88]
**Describe the bug**
This is not a bug but a question.

Is it possible to use `lua require"illuminate".next_reference{wrap=true}` on buffers without lsp active? I can see that highlighting works with/without lsp. So, for these can we jump through these highlights?

**Comment by RRethy** [comment]
No, this is specific to LSP functionality.

**Comment by Massolari** [comment]
I want this too! Maybe there is a solution to this
