### ISSUE TITLE
border around the word highlighted

### ISSUE THREAD

**Issue by jrafaaael** [RRethy/vim-illuminate#91]
I want to reproduce the behavior of VSCode for highlight the word under the cursor with a border (and the highlight color):
![Screenshot at 2022-01-03 18-48-27](https://user-images.githubusercontent.com/70046023/147988723-3159d6c2-948e-4199-9888-332ebbed3274.png)
With this plugin I can highlight the word. I there any way to put the border around of these?

**Comment by RRethy** [comment]
This isn't possible in a terminal and Neovim doesn't provide a way to do this for GUIs.

**Comment by jrafaaael** [comment]
@RRethy thank you!
